// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfZ837015DXxtJ1_obgqbf2NmSNiWLgOc',
    appId: '1:179905458552:web:faea0837a43b094235988d',
    messagingSenderId: '179905458552',
    projectId: 'hereforyou-ae170',
    authDomain: 'hereforyou-ae170.firebaseapp.com',
    databaseURL: 'https://hereforyou-ae170-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hereforyou-ae170.appspot.com',
    measurementId: 'G-BKGVTWZ27F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdGM0AU8FS_UJ5msjyGoJ0Qat9BgbCDrg',
    appId: '1:179905458552:android:caa41fed3443914435988d',
    messagingSenderId: '179905458552',
    projectId: 'hereforyou-ae170',
    databaseURL: 'https://hereforyou-ae170-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hereforyou-ae170.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhI_a7JSTDxVrUxmLsF85_XIy2Ef_S6n4',
    appId: '1:179905458552:ios:3b5fe265e7ff8b2f35988d',
    messagingSenderId: '179905458552',
    projectId: 'hereforyou-ae170',
    databaseURL: 'https://hereforyou-ae170-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hereforyou-ae170.appspot.com',
    iosClientId: '179905458552-3o6mmh7unec0359die8o6odoeercmavf.apps.googleusercontent.com',
    iosBundleId: 'com.example.hereForu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhI_a7JSTDxVrUxmLsF85_XIy2Ef_S6n4',
    appId: '1:179905458552:ios:3b5fe265e7ff8b2f35988d',
    messagingSenderId: '179905458552',
    projectId: 'hereforyou-ae170',
    databaseURL: 'https://hereforyou-ae170-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hereforyou-ae170.appspot.com',
    iosClientId: '179905458552-3o6mmh7unec0359die8o6odoeercmavf.apps.googleusercontent.com',
    iosBundleId: 'com.example.hereForu',
  );
}
